version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Compile Java Program
          command: javac src/HelloWorld.java
      - run:
          name: Run Java Program
          command: java -cp src HelloWorld
